---

# API version of Docker compose
version: "3"

# Define the services
services:
  db:
    image: mysql:latest
    volumes:
      - ./home/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: amitdalal@123
      MYSQL_DATABASE: wordpress
    cap_add:
      - SYS_NICE
      
      
    ports:
      - "3306:3306"
    networks:
      - app-network
    expose:
      - "3306"
    
    
      # ... other environment varia
# API block starts here
  api:
    image: "amitdalal/alpine-nginx-php" # Docker image for API
    volumes:
     - /home/wp:/var/www/html
    expose:
      - 8080
    depends_on: 
     - db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: amitdalal@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: amitdalal
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
